name: Review Listing Request

on:
  issues:
    types: [opened, labeled, reopened]

permissions: {}

jobs:
  review-listing-request:
    if: contains(github.event.label.name, 'listing-request')
    runs-on: ubuntu-latest
    permissions:
      issues: write
      contents: read
    steps:
      - name: Checkout this repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Install uv
        uses: astral-sh/setup-uv@85856786d1ce8acfbcc2f13a5f3fbd6b938f9f41  # v7.1.2

      - name: Install runners
        run: |
          sudo snap install just --classic
          uv tool install tox --with tox-uv

      - name: Authenticate GitHub CLI
        run: echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token

      - name: Update issue summary and description
        env:
            GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
            # TODO: This is not the best way to run the script, we should clean this up, but just
            # getting it working for now.
            uv venv
            uv pip install .
            uv run update-issue --issue-number "${{ github.event.issue.number }}"
